.fix <- function(x){
  x <- tolower(x) %>% str_replace_all(., "[[:punct:]]", "_")
  return(x)
}


#' Function to check samplesheet for nf-core
#'
#' @param file path to CSV file for nf-core
#' @examples
#'
#' bcbio_nfcore_check(system.file("extdata", "rnaseq_good.csv", package = "bcbioR") )
#'
#' @export
bcbio_nfcore_check <- function(file){
  required=c("sample","fastq_1","fastq_2","strandedness")
  samplesheet=read_csv(file)

  if (!(all(required %in% colnames(samplesheet)))){
    print(colnames(samplesheet))
    stop("Missing required columns ", paste(required, collapse = " "))
  }else if (any(grepl("^[1-9]", samplesheet[["sample"]]))){
    stop("Avoid samples starting with numbers ")
  }else if (any(is.na(samplesheet))){
    warning("Columns with missing values")
  }else{
    message("All good.")
  }
}

#' Function to help deploy analysis folder inside a project folder
#'
#' This function contains Rmd, R, md, files that help to structure
#' an analysis following HCBC best-practices.
#' For rnaseq, it will deploy: QC and DE Rmd with additional files to help
#'   to facilitate the analysis as needed.
#'
#' Normally these helper files are inside a report folder inside a
#' project folder.
#'
#' @param type string indicating the type of analysis, supported: rnaseq.
#'
#' @param outpath string path indicating where to copy all the files to
#' @examples
#'  \dontrun{
#'  bcbio_templates("rnaseq", "path_to_projects/project1/reports")
#'  }
#' @export
bcbio_templates <- function(type="rnaseq", outpath){
  switch(type,
         rnaseq={

           fpath <- system.file("rmarkdown/templates/rnaseq", "skeleton", package="bcbioR")
           #file.copy(fpath, outpath, recursive = T)
           copyDirectory(fpath, outpath)
         },
         scrnaseq={

           fpath <- system.file("rmarkdown/templates/singlecell", "skeleton", package="bcbioR")
           #file.copy(fpath, outpath, recursive = T)
           copyDirectory(fpath, outpath)
         },
         {
           stop('project type not recognize, please choose: ', 'rnaseq', 'scrnaseq')
         }
  )
}

#' Function to help with project name used for parent folder
#'
#' This function will ask for user input about:
#'   * numeric code
#'   * PI full name
#'   * technology
#'   * tissue
#'   * organism
#'   * project description
#'
#' It removes special character with `_`. The output is a guideline to
#'   what the folder used can be.
#'
#' @returns A string list with hbc_code, and project folder name
#' @export
bcbio_set_project <- function() {
  hbc_code <- readline("What is the hbc code (only numbers):\n")
  hbc_code <- paste0("hbc", hbc_code)
  pi <- readline("What is PI last name:\n")
  technology <- readline("What is the technology:\n")
  tissue <- readline("What is the tissue:\n")
  org <- readline("What is the organism:\n")
  project <- readline("What is the project name:\n")
  #dropbox <- readline("What is the dropbox name:\n")
  #github_org <- readline("What is the github organization:\n")
  #hbc_$technology_of_$pilastname_$intervention_on_$tissue_in_$organism_$hbccode
  project_full <- paste(technology, .fix(pi), .fix(project), tissue, org, hbc_code, sep="_")
  #github <- c(github_org,project_full)
  opts <- list(code=hbc_code, project=project_full)
               #dropbox=file.path(dropbox,project_full),
               #github=github)
  print(opts)
  return(opts)
}


bcbio_start_project <- function(options) {

}

bcbio_gitignore <- function(options) {

}

# This function showcases how one might write a function to be used as an
# RStudio project template. This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/hello_world.dcf
#
# The function itself just echos its inputs and outputs to a file called INDEX,
# which is then opened by RStudio when the new project is opened.
rnaseq <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header
  header <- c(
    "# This file was generated by a call to 'ptexamples::hello_world()'.",
    "# The following inputs were received:",
    ""
  )

  # collect inputs
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "README.md"))

}
